# Generated by Django 4.1.6 on 2023-06-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='date_posted',
        ),
    ]
